### ISSUE TITLE
Timeout (milliseconds) is being checked against PHP max_execution_time (seconds)

### ISSUE THREAD

**Issue by jf-paquin-web** [loveOSS/resiliency#58]
In MainSystem, the timeout is defined in milliseconds. 
In MainSystem::validateTimeout(), we compare the value with PHP max_execution_time, which is defined in seconds. 

This means if the max_execution_time is 300 seconds, the maximum valid timeout is 300ms.

**Comment by mickaelandrieu** [comment]
Hi,

does it fix the bug ?

I'm not sure how to test it tbh ... https://github.com/loveOSS/resiliency/pull/59

Regards

**Comment by jf-paquin-web** [comment]
@mickaelandrieu 
That was quick! Yes this should do it 👍 

Merci!

**Comment by mickaelandrieu** [comment]
Thanks for your feedback, I've releases v2.2 with the patch.
