### ISSUE TITLE
[Idea] More flexible configuration for state change.

### ISSUE THREAD

**Issue by eortiz-tracktik** [loveOSS/resiliency#61]
Hello @mickaelandrieu, thanks a lot for developing this great library. 

Have you considered a more sophisticated approach like having the possibility of looking at frequency of errors, tripping once you get, say, a 5% failure rate. You might also have different thresholds for different errors, such as a threshold of 10 for timeouts but 3 for connection failures?

**Comment by mickaelandrieu** [comment]
Hello @eortiz-tracktik ,

using the provided events I think you _may_ have this kind of approach or do I miss something here ?

Regards

**Comment by eortiz-tracktik** [comment]
Fast response @mickaelandrieu 

I didn't understand how to use them :sweat_smile: 
I see on the README.md the Use section that specify the available parameters for the circuit breaker configuration
```
    the failures: define how many times we try to access the service;
    the timeout: define how long we wait (in ms) before consider the service unreachable;
    the stripped timeout: define how long we wait (in ms) before consider the service unreachable, once we're in half open state;
    the threshold: define how long we wait (in ms) before trying to access again the service;
    the (HTTP|HTTPS) client that will be used to reach the services;
    the fallback callback will be used if the distant service is unreachable when the Circuit Breaker is Open (means "is used").
```

If you want to use a 5% failure rate for timeouts and 3% for connection failures how do you will do it using the events?

**Comment by mickaelandrieu** [comment]
Hmm you may listen to the Tried event but it's not enough as you don't have access to the type of exception...

**Comment by mickaelandrieu** [comment]
Resiliency 2.3 have been released : this should help you to do what you want (even if it's not great regarding the developer experience).
